version: '3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6000:6000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres_db:5432/comerseprojectdb
      - APP_ID=6000
      - JWT_ACCESS_KEY=wqediqw;iod
      - JWT_REFRESH_KEY=qndqwdbqud
      - JWT_ADMIN_ACCESS_KEY=AHNJFukajwgU
      - JWT_ADMIN_REFRESH_KEY=aqojdwijijdijijdij
      - ADMIN_LOGIN=Chuvirla
      - ADMIN_PASSWORD=besperspektivnyak
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:latest
    container_name: PostgresContainer
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: comerseprojectdb
    volumes:
      - postgres_db:/var/lib/postgresql/data

volumes:
  postgres_db: